### ISSUE TITLE
how is this useful?

### ISSUE THREAD

**Issue by freakeinstein** [indix/whatthelang#11]
You are using Fasttext for language classification. While examining the README example, I see the input text is given in corresponding unicode characters. I'm being curious that, how it differentiate itself from a logic that uses character parser to determine language?

**Comment by whiletruelearn** [comment]
@freakeinstein A language parser built on top of rules would be difficult to maintain over the long run. Also for languages which has high lexical similarity , identifying which is which is going to be difficult. 
Fasttext, since it supports char- ngram is in effect containing rules at an abstract level for us to do this differentiation. 

For completeness , [Langdetect](https://github.com/Mimino666/langdetect/tree/master/langdetect/profiles) a popular project for Language detection uses NB for classification , but it needs a profile for each language to be built which is different char-N grams with frequency. With Fasttext quantized models , you can treat language detection  as a text classification problem itself and since the model sizes are small , it can be shipped easily as a python package.
