### ISSUE TITLE
pyfasttext dependecy issue for mac OS users

### ISSUE THREAD

**Issue by nazariyv** [indix/whatthelang#9]
Hi,

Can you change this dependency to something that uses another binding of fasttext? It looks like pyfasttext is using old version of fasttext (pre 0.8.2) and so mac os users get the symbol not found error: https://github.com/vrasneur/pyfasttext/issues/46. So I cannot use this on my mac..

**Comment by whiletruelearn** [comment]
@nazariyv , the latest binding of fasttext which facebook is developing is also not pushed to [PyPi](https://github.com/facebookresearch/fastText/issues/560). If you look at release history, pyfasttext is actually newer than the default `fasttext` binding. 

The symbol error is usually  because of some Cython dependency not being correctly installed and IIRC pyfasttext is tested to be working in mac. I have seen that you have raised an issue in pyfasttext. Let's continue the discussion there.  

For now I am closing this as this is a dependency issue.
